// The share grant envelope (docs/crypto.md §"Share grant envelope") is
// genuinely Worker-side crypto
// -- the Worker is the only party holding SHARE_GRANT_KEY, so it's the
// only party that can ever produce or open a grant.
import { describe, expect, it } from "vitest";
import { openGrant, sealGrant } from "../shareGrant";

function randomBytes(length: number): Uint8Array {
  return crypto.getRandomValues(new Uint8Array(length));
}

describe("shareGrant", () => {
  it("round-trips the exact object path under a fixed key and idHash", async () => {
    const shareGrantKey = randomBytes(32);
    const idHash = randomBytes(32);
    const objectPath = "abcd1234/shared/efgh5678";

    const envelope = await sealGrant(objectPath, idHash, shareGrantKey);
    const decoded = await openGrant(envelope, idHash, shareGrantKey);

    expect(decoded).toBe(objectPath);
  });

  it("produces a different salt, nonce, and ciphertext on each seal call", async () => {
    const shareGrantKey = randomBytes(32);
    const idHash = randomBytes(32);
    const objectPath = "same/path/every/time";

    const envelopeA = await sealGrant(objectPath, idHash, shareGrantKey);
    const envelopeB = await sealGrant(objectPath, idHash, shareGrantKey);

    expect([...envelopeA]).not.toEqual([...envelopeB]);
  });

  it("rejects opening under the wrong shareGrantKey", async () => {
    const shareGrantKey = randomBytes(32);
    const wrongKey = randomBytes(32);
    const idHash = randomBytes(32);
    const envelope = await sealGrant("some/path", idHash, shareGrantKey);

    await expect(openGrant(envelope, idHash, wrongKey)).rejects.toThrow();
  });

  // The specific anti-replay property docs/crypto.md describes: a grant is
  // bound to the share_id it was sealed for via both the HKDF `info` and
  // the AEAD additional data. Reproduce the exact scenario -- a grant
  // sealed for one share, decryption attempted under a different share's
  // idHash -- rather than only testing "wrong key" above.
  it("rejects opening a grant under a different idHash than it was sealed for", async () => {
    const shareGrantKey = randomBytes(32);
    const idHash = randomBytes(32);
    const otherIdHash = randomBytes(32);
    const envelope = await sealGrant("some/path", idHash, shareGrantKey);

    await expect(openGrant(envelope, otherIdHash, shareGrantKey)).rejects.toThrow();
  });

  it("rejects a envelope shorter than the minimum length", async () => {
    await expect(
      openGrant(new Uint8Array(10), randomBytes(32), randomBytes(32)),
    ).rejects.toThrow(/too short/);
  });

  it("rejects an envelope with an unsupported version byte", async () => {
    const shareGrantKey = randomBytes(32);
    const idHash = randomBytes(32);
    const envelope = await sealGrant("some/path", idHash, shareGrantKey);
    envelope[0] = 0x02;

    await expect(openGrant(envelope, idHash, shareGrantKey)).rejects.toThrow(
      /unsupported grant version/,
    );
  });

  it("rejects a tampered salt", async () => {
    const shareGrantKey = randomBytes(32);
    const idHash = randomBytes(32);
    const envelope = await sealGrant("some/path", idHash, shareGrantKey);
    envelope[5] ^= 0xff; // inside the salt field (offset 1..33)

    await expect(openGrant(envelope, idHash, shareGrantKey)).rejects.toThrow();
  });

  it("rejects a tampered sealed ciphertext/tag", async () => {
    const shareGrantKey = randomBytes(32);
    const idHash = randomBytes(32);
    const envelope = await sealGrant("some/path", idHash, shareGrantKey);
    envelope[envelope.length - 1] ^= 0xff; // inside the trailing GCM tag

    await expect(openGrant(envelope, idHash, shareGrantKey)).rejects.toThrow();
  });

  // Pinned once and committed: catches a future refactor that silently
  // changes the envelope's byte layout, which none of the round-trip tests
  // above would catch (they always encrypt and decrypt with the same,
  // possibly-also-changed code).
  it("decrypts a known-answer fixture generated by this same implementation", async () => {
    const shareGrantKey = new Uint8Array(32);
    for (let i = 0; i < 32; i++) shareGrantKey[i] = i;
    const idHash = new Uint8Array(32);
    for (let i = 0; i < 32; i++) idHash[i] = 255 - i;
    const objectPath =
      "abcd1234efgh5678/shared/wxyz9876mnop5432wxyz9876mnop5432wxyz9876mnop5432wx";
    const envelopeHex =
      "01070a0d101316191c1f2225282b2e3134373a3d404346494c4f5255585b5e6164121518" +
      "1b1e2124272a2d3033e6681fa3c5d4584f4705239516ad414f0e94fdf7f584dab2edd591" +
      "3b2b9fedfc8e59bd98739e956544e7c9b2787fc8f10e28c6c1d89f54fba8818d3fc4c2c2" +
      "81ab9690d132a92eac182a6c0e53ef33beb140f74b61f6027fb198";
    const envelope = new Uint8Array(
      envelopeHex.match(/.{2}/g)!.map((byte) => parseInt(byte, 16)),
    );

    expect(envelope.length).toBe(135);
    await expect(openGrant(envelope, idHash, shareGrantKey)).resolves.toBe(objectPath);
  });
});
