// wrangler.jsonc has no [vars] block for secrets on purpose -- their real
// values are set as Cloudflare dashboard Variables and Secrets, never
// committed to this repo. `wrangler types` only knows about bindings
// declared in wrangler.jsonc (worker-configuration.d.ts, regenerated by
// `wrangler types` -- do not hand-edit that file), so this interface merges
// in the vars/secrets the Worker expects at runtime. Grows as later steps
// add ctl/Turso access and KV caching.
interface Env {
  FIREBASE_PROJECT_ID: string;
  CTL_DB_URL: string;
  CTL_DB_TOKEN: string;
  TURSO_ORG_TOKEN: string;
  TURSO_ORG: string;
  // r2Token.ts's parent credential -- the admin's own static R2 read-write
  // key, held only here. Never sent to any client; every client-visible
  // credential is a short-lived, scoped JWT minted from it.
  R2_ENDPOINT: string;
  R2_BUCKET: string;
  R2_READ_WRITE_ACCESS_KEY_ID: string;
  R2_READ_WRITE_SECRET_ACCESS_KEY: string;
}
