// wrangler.jsonc has no [vars] block for secrets on purpose -- their real
// values are set as Cloudflare dashboard Variables and Secrets, never
// committed to this repo. `wrangler types` only knows about bindings
// declared in wrangler.jsonc (worker-configuration.d.ts, regenerated by
// `wrangler types` -- do not hand-edit that file), so this interface merges
// in the vars/secrets the Worker expects at runtime (docs/auth.md §1).
interface Env {
  FIREBASE_PROJECT_ID: string;
  ADMIN_UID: string;
  SHARE_GRANT_KEY: string;
  SHARE_REGISTRY: D1Database;
  SHARE_RATE_LIMITER: RateLimit;
  CTL_DB_URL: string;
  CTL_DB_TOKEN: string;
  // Standard padded base64 encoding of at least 32 random bytes.
  R2_TICKET_SECRET: string;
  R2_ENDPOINT: string;
  R2_BUCKET: string;
  R2_REGION: string;
  // r2Token.ts's parent credential -- the admin's own static R2 read-write
  // access key, held only here. Never sent to any client; every
  // client-visible credential is a short-lived JWT minted from it, scoped
  // down by what's signed into it rather than by which parent key signs it.
  R2_READ_WRITE_ACCESS_KEY_ID: string;
  R2_READ_WRITE_SECRET_ACCESS_KEY: string;
  KEYS_CACHE: KVNamespace;
}
