// wrangler.jsonc has no [vars] block for these on purpose -- their real
// values are set as Cloudflare dashboard Variables and Secrets, never
// committed to this repo. R2_BUCKET/R2_ENDPOINT/FIREBASE_PROJECT_ID are not
// themselves sensitive, but they live alongside the two real secrets rather
// than in wrangler.jsonc so there's one configuration surface, not two).
// `wrangler types` only knows
// about bindings declared in wrangler.jsonc (worker-configuration.d.ts,
// regenerated by `wrangler types` -- do not hand-edit that file), so this
// interface merges in the vars r2Creds.ts expects at runtime.
interface Env {
  READ_WRITE_ACCESS_KEY_ID: string;
  READ_WRITE_SECRET_ACCESS_KEY: string;
  R2_BUCKET: string;
  // e.g. https://<accountId>.r2.cloudflarestorage.com
  R2_ENDPOINT: string;
  // Pins the issuer/audience verifyFirebaseIdToken checks a token's claims
  // against -- must never be accepted from the request itself (see
  // r2Creds.ts's comment on verifyFirebaseIdToken for why).
  FIREBASE_PROJECT_ID: string;
}
